.apex/unpackaged/objects/Comment__c.object
<CustomObject>
    <fields>
        <fullName>Photo__c</fullName>
        <label>Photo</label>
        <referenceTo>Photo__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.apex/unpackaged/objects/Photo__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Photo</label>
    <nameField>
        <displayFormat>PH-{0000}</displayFormat>
        <label>Photo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Photos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.apex/unpackaged/classes/ShowPhotoController.cls
/**
 * Created by patryk on 2018-11-16.
 */
public class ShowPhotoController {

	public Photo__c photo{
		get{
			return [SELECT Name__c, Source__c from Photo__c where Id=:photoId].get(0);
		}
		set;
	}



	public List<Comment__c> comments{
		get{
			return [SELECT CreatedDate,Text__c from Comment__c where Photo__c=:photoId Order BY CreatedDate desc];
		}
		set;
	}

	public String photoId;
	public String commText{get;set;}


	public ShowPhotoController() {
		try {
			photoId = ApexPages.currentPage().getParameters().get('id');

		} catch (Exception e) {
		}

	}

	public PageReference addComment(){
		Comment__c comm= new Comment__c();
		comm.Photo__c=photoId;
		comm.Id=null;
		comm.Text__c=commText;
		insert comm;
		commText='';
		return null;
	}
}