.apex/unpackaged/objects/Patient__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_name__c</fullName>
        <label>Last name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/PatientDAO.cls
/**
 * Created by patryk on 2018-11-14.
 */

@RestResource(urlMapping='/Patient/*')
global class PatientDAO {

	@HttpPost
	global static Boolean addPatient(String firstName, String lastName){

		Patient__c p = new Patient__c();
		p.First_Name__c = firstName;
		p.Last_name__c = lastName;

		try{
			insert p;
		}
		catch (Exception ex){
			return false;
		}
		return true;
	}

	@HttpGet
	global static List<Patient__c> selectPatient(){
		RestRequest req = RestContext.request;
		String Id = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);

		if(Id.length()!=0){
			return [Select p.Id,p.First_Name__c,p.Last_name__c from Patient__c p where p.Id=:Id];
		}
		return [Select p.Id,p.First_Name__c,p.Last_name__c from Patient__c p ];
	}

	@HttpDelete
	global static boolean deletePatient(){
		RestRequest req = RestContext.request;
		String ID = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
		try{
			delete [SELECT ID from Patient__c where Id=:ID];
		}catch (Exception ex){
			return false;
		}
		return true;
	}

	@HttpPut
	global static boolean updatePatient(String firstName, String lastName, String ID){
		try{
			Patient__c p = new Patient__c();
			p.First_Name__c=firstName;
			p.Last_name__c=lastName;
			p.Id=ID;
			upsert p;
		}catch (Exception ex){
			return false;
		}
		return true;
	}


}