unpackaged/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_name__c</fullName>
        <label>Last name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Admin</fullName>
                    <default>true</default>
                    <label>Admin</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Doctor</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Doctor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/CreateUserHandler.cls
/**
 * Created by patryk on 2018-11-15.
 */
public class CreateUserHandler {

	public static String createUser(String fn, String ln, String password) {
		System.debug(fn);
		System.debug(ln);
		System.debug(password);
		Doctor__c doc = new Doctor__c();
		doc.First_Name__c = fn;
		doc.Last_name__c = ln;
		doc.Password__c = CryptoHandler.hashToSHA256(password);
		doc.Role__c = 'Admin';
		try {
			insert doc;

			String name = [Select Name from Doctor__c where Id=:doc.Id].get(0).Name;
			System.debug(name);
			return name;
		} catch (Exception e) {
			return '';
		}

		return null;
	}
}