unpackaged/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_name__c</fullName>
        <label>Last name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Admin</fullName>
                    <default>true</default>
                    <label>Admin</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Doctor</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Doctor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/unpackaged/objects/Patient__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_name__c</fullName>
        <label>Last name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                    <default>true</default>
                    <label>User</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Patient</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/AddPatientController.cls
/**
 * Created by patryk on 2018-11-17.
 */
public class AddPatientController {


	private static final String HOME_PAGE = '/apex/HomePage';
	private static final String DETAILS_PAGE = '/apex/PatientDetails';


	public Boolean success{
		get;set;
	}

	public Patient__c patient {
		get;set;
	}

	public String password{
		get;set;
	}

	public String password2{
		get;set;
	}

	private String doctorId;

	public AddPatientController() {
		patient = new Patient__c();
		try {
			doctorId = ApexPages.currentPage().getParameters().get('docId');
		} catch (Exception e) {
		}
	}

//
//	public PageReference back() {
//		PageReference pageRef = new PageReference(HOME_PAGE);
//		pageRef.setRedirect(true);
//		pageRef.getParameters().put('id', doctorId);
//		return pageRef;
//	}

	public PageReference save() {
		if (password.equals(password2) && password.length() > 6) {

			System.debug(patient);

			if (patient.First_Name__c.length() > 0 && patient.Last_name__c.length() > 0) {
				patient.Password__c = CryptoHandler.hashToSHA256(password);
				patient.Role__c = 'User';
				patient.Doctor__c = doctorId;
				insert patient;
			} else {
				success = false;
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'First and Last Name cannot be empty !'));
			}
		} else {
			success = false;
			ApexPages.addMessage(
					new ApexPages.Message(ApexPages.Severity.ERROR, 'Password must be at least 6 characters !'));
		}

		System.debug(patient);

		PageReference pageRef = new PageReference(DETAILS_PAGE);
		pageRef.setRedirect(true);
		pageRef.getParameters().put('id', patient.Id);
		pageRef.getParameters().put('docId', doctorId);
		return pageRef;


	}


}