unpackaged/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_name__c</fullName>
        <label>Last name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Doctor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/DoctorDAO.cls
/**
 * Created by patryk on 2018-11-18.
 */
@RestResource(urlMapping = '/Doctor/*')
global class DoctorDAO {

	@HttpGet
	global static Doctor__c seledtDoctor() {
		RestRequest req = RestContext.request;
		String Login = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);

		List<Doctor__c> doctor = [Select Name,First_Name__c,Last_name__c,Password__c from Doctor__c where Name=:Login];
		if(doctor.size()>0){
			return doctor.get(0);
		}
		return null;

	}

}