unpackaged/objects/Examination__c.object
<CustomObject>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Examinations</relationshipLabel>
        <relationshipName>Examinations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Examination</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Examination  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Examinations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.apex/unpackaged/objects/Patient__c.object
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/unpackaged/classes/AddExamController.cls
/**
 * Created by patryk on 2018-11-17.
 */
public class AddExamController {

	private static final String DETAILS_PAGE = '/apex/PatientDetails';


	public Boolean success{
		get;set;
	}

	public Examination__c exam {
		get;set;
	}

	private String doctorId;
	private String patientId;

	public AddExamController() {
		exam = new Examination__c();
		try {
			doctorId = ApexPages.currentPage().getParameters().get('docId');
			patientId = ApexPages.currentPage().getParameters().get('id');
		} catch (Exception e) {
		}
	}

	public PageReference save() {

		exam.Patient__c = patientId;
		insert exam;


		PageReference pageRef = new PageReference(DETAILS_PAGE);
		pageRef.setRedirect(true);
		pageRef.getParameters().put('id', patientId);
		pageRef.getParameters().put('docId', doctorId);
		return pageRef;


	}
}