unpackaged/objects/Examination__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Examinations</relationshipLabel>
        <relationshipName>Examinations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Examination</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Examination  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Examinations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.apex/unpackaged/objects/Patient__c.object
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/unpackaged/classes/ExaminationDAO.cls
/**
 * Created by patryk on 2018-11-20.
 */
@RestResource(urlMapping = '/Examinations/*')
global class ExaminationDAO {

	@HttpGet
	global static List<Examination__c> selectExaminations() {
		RestRequest req = RestContext.request;
		String docID = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);

		List<Examination__c> examinations = [Select Id,Name,Name__c,Description__c from Examination__c where Patient__c=:docID];
		return examinations;

	}

}