unpackaged/objects/Examination__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Examinations</relationshipLabel>
        <relationshipName>Examinations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Examination</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Examination  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Examinations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.apex/unpackaged/objects/Patient__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_name__c</fullName>
        <label>Last name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/unpackaged/classes/PatientDetailsController.cls
/**
 * Created by patryk on 2018-11-16.
 */
public class PatientDetailsController {

	private String patientId;
	private String doctorId;

	private static final String HOME_PAGE = '/apex/HomePage';
	private static final String ADD_EXAM_PAGE = '/apex/AddExamPage';
	private static final String SELF_PAFE = '/apex/PatientDetails';
	private static final String PHOTO_PAGE = '/apex/PhotosPage';

	public String selectedExam{get;set;}

	public Patient__c patient{
		get;
		set;
	}

	public Boolean edittEnable{
		get;set;
	}

	public List<Examination__c> exam{get{
		return [Select Name,Name__c,Description__c,CreatedDate from Examination__c where Patient__r.Id=:patientId];
	}}

	public PatientDetailsController() {

		try {
			patientId = ApexPages.currentPage().getParameters().get('id');
			doctorId = ApexPages.currentPage().getParameters().get('docId');
			edittEnable = false;
			patient = [Select Name,First_Name__c, Last_name__c from Patient__c where Id=:patientId].get(0);
		} catch (Exception e) {
		}
	}

	public PageReference updatePatient() {
		try {
			update patient;
		} catch (Exception e) {
		}
		PageReference pageRef = new PageReference(SELF_PAFE);
		pageRef.setRedirect(true);
		pageRef.getParameters().put('docId', doctorId);
		pageRef.getParameters().put('id', patientId);
		return pageRef;
	}

	public PageReference examPhotos(){
		PageReference pageRef = new PageReference(PHOTO_PAGE);
		pageRef.setRedirect(true);
		pageRef.getParameters().put('id', selectedExam);
		pageRef.getParameters().put('docId', doctorId);
		return pageRef;
	}

	public PageReference newExam(){
		PageReference pageRef = new PageReference(ADD_EXAM_PAGE);
		pageRef.setRedirect(true);
		pageRef.getParameters().put('id', patientId);
		pageRef.getParameters().put('docId', doctorId);
		return pageRef;
	}


	public PageReference back(){
		PageReference pageRef = new PageReference(HOME_PAGE);
		pageRef.setRedirect(true);
		pageRef.getParameters().put('id', doctorId);
		return pageRef;
	}

}