unpackaged/objects/Examination__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Examinations</relationshipLabel>
        <relationshipName>Examinations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Examination</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Examination  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Examinations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.apex/unpackaged/objects/Patient__c.object
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/unpackaged/objects/Photo__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Examination__c</fullName>
        <label>Examination</label>
        <referenceTo>Examination__c</referenceTo>
        <relationshipLabel>Photos</relationshipLabel>
        <relationshipName>Photos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Photo</label>
    <nameField>
        <displayFormat>PH-{0000}</displayFormat>
        <label>Photo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Photos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/PhotosController.cls
/**
 * Created by patryk on 2018-11-16.
 */
public class PhotosController {

	private static final String DETAILS_PAGE = '/apex/PatientDetails';
	private static final String PHOTO_PAGE = '/apex/ShowPhotoPage';

	public String examID;
	public String docId;

	public String selectedPhoto{
		get;set;
	}

	public List<Photo__c> photos{
		get{
			return [SELECT Id,Name,Name__c,Description__c,Source__c,CreatedDate from Photo__c where Examination__r.Id=:examID order by CreatedDate desc] ;
		}
	}
	public Examination__c exam{
		get{
			return [SELECT Patient__r.Id,Name from Examination__c where Id=:examID];
		}
	}

	public PhotosController() {
		try {
			examID = ApexPages.currentPage().getParameters().get('id');
			docId = ApexPages.currentPage().getParameters().get('docId');
		} catch (Exception e) {
		}
	}

	public PageReference show() {
		PageReference pageRef = new PageReference(PHOTO_PAGE);
		pageRef.setRedirect(true);
		pageRef.getParameters().put('id', selectedPhoto);
		return pageRef;
	}

	public PageReference back() {
		PageReference pageRef = new PageReference(DETAILS_PAGE);
		pageRef.setRedirect(true);
		pageRef.getParameters().put('id', exam.Patient__r.Id);
		pageRef.getParameters().put('docId', docId);
		return pageRef;
	}
}